# Generated by Django 5.2.12 on 2026-03-09 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('views', models.IntegerField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('drip_score', models.FloatField(default=0)),
                ('top_image', models.ImageField(upload_to='outfits/')),
                ('bottom_image', models.ImageField(upload_to='outfits/')),
                ('top_link', models.URLField(blank=True, null=True)),
                ('bottom_link', models.URLField(blank=True, null=True)),
                ('source', models.CharField(choices=[('affiliate', 'Affiliate'), ('custom', 'Custom Combo')], default='custom', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
