# Generated by Django 5.2.12 on 2026-03-12 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_stylecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stylecategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Style Category', 'verbose_name_plural': 'Style Categories'},
        ),
        migrations.AddField(
            model_name='stylecategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls ordering in UI'),
        ),
        migrations.AddField(
            model_name='stylecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stylecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stylecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name used in frontend UI', max_length=100),
        ),
        migrations.AlterField(
            model_name='stylecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='UserStyleInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_style_interests', to='outfits.stylecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'style')},
            },
        ),
    ]
