# Generated by Django 5.2.12 on 2026-03-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0003_alter_stylecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylecategory',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
