# Generated by Django 5.2.12 on 2026-03-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0004_alter_stylecategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stylecategory',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='stylecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='style_categories/'),
        ),
        migrations.AlterField(
            model_name='stylecategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stylecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional icon name used in frontend UI', max_length=100),
        ),
    ]
