# Generated by Django 5.2.12 on 2026-03-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drips', '0002_drip_is_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='drip',
            name='community_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='drip',
            name='rating_sum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='drip',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='drip',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
